baseURL = "http://news.starcoin.org/"
languageCode = "zh"
title = "Starcoin News"
DefaultContentLanguage = "zh"
defaultContentLanguageInSubdir = true
#theme = "anatole"


theme = "jeffprod"
#canonifyurls = true
#paginate = 3
features = ["pagination","archives","tags"]
[taxonomies]
    tag = "tags"
    archive = "archives"
[permalinks]
    post = "/:year/:filename"


enableGitInfo = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Starcoin News"
    weight = 10
  [languages.zh]
    languageName = "Chinese"
    title = "Starcoin 新闻"
    weight = 20
