baseURL = "http://news.starcoin.org/"
languageCode = "en"
title = "Starcoin News"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
#theme = "anatole"


theme = "jeffprod"
[permalinks]
    post = "/:year/:filename"

[taxonomies]
    tag = "tags"
    archive = "archives"


enableGitInfo = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Starcoin News"
    weight = 10
  [languages.zh]
    languageName = "Chinese"
    title = "Starcoin 新闻"
    weight = 20
