baseURL = "https://starcoin-news.github.io"
languageCode = "en"
title = "Starcoin News"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "hugo-swift-theme"
enableGitInfo = false

[languages]
  [languages.en]
    languageName = "English"
    title = "Starcoin News"
    weight = 10
  [languages.zh]
    languageName = "Chinese"
    title = "Starcoin 新闻"
    weight = 20
